server:
  port: 8081

#person:
#  lastName: zhangsan
#  age: 18
#  boss: false
#  birth: 2017/2/8
#  maps: {k1: v1, k2: v2}
#  lists:
#    - zhaoliu
#    - lisi
#  dog:
#    name: 小狗
#    age: 10