spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.2.6:3306/jdbc
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:department.sql